tap "homebrew/cask"

cask "brave-browser"
cask "iterm2"
cask "osxfuse"
cask "appcleaner"
cask "bettertouchtool"
cask "sublime-text"
cask "java"
cask "vlc"
cask "the-unarchiver"
# cask "steam"
# cask "balenaetcher"
# cask "android-platform-tools"


brew "zsh"
brew "tmux"
brew "coreutils"
brew "nano"
brew "tree"
brew "autoconf"
brew "automake"
brew "fzf"
brew "htop"
brew "iperf3"
brew "midnight-commander"
brew "mkvtoolnix"
brew "media-info"
brew "nmap"
brew "netcat"
brew "tig"
brew "wakeonlan"
brew "wget"
brew "youtube-dl"
brew "ripgrep"
# brew "magic-wormhole"
# brew "kubectl"