tap "homebrew/cask"

cask "firefox"
cask "steam"
cask "iterm2"
cask "osxfuse"
cask "balenaetcher"
cask "appcleaner"
cask "bettertouchtool"
cask "sublime-text"
cask "java"
cask "vlc"
cask "android-platform-tools"
cask "the-unarchiver"


brew "zsh"
brew "tmux"
brew "coreutils"
brew "tree"
brew "autoconf"
brew "automake"
brew "fzf"
brew "htop"
brew "iperf3"
brew "magic-wormhole"
brew "midnight-commander"
brew "mkvtoolnix"
brew "media-info"
brew "nmap"
brew "netcat"
brew "tig"
brew "wakeonlan"
brew "wget"
brew "youtube-dl"
